article/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from api import ArticleResource

article_resource = ArticleResource()

urlpatterns = patterns('',
    url(r'^all/$', 'article.views.articles'),
    url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^language/(?P<language>[a-zA-Z\-]+)/$', 'article.views.language'),
    url(r'^(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^create/$', 'article.views.create'),
    url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
    url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
    url(r'^search/$', 'article.views.search_titles'),
    url(r'^api/', include(article_resource.urls)),
)

django_test/urls.py
from django.conf.urls import patterns, include, url
from article.views import HelloTemplate

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# For Formwizard:
from django_test.forms import ContactForm1, ContactForm2, ContactForm3
from django_test.views import ContactWizard

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_test.views.home', name='home'),
    # url(r'^django_test/', include('django_test.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^article/', include('article.urls')),
    url(r'^articles/', include('article.urls')),
    url(r'^accounts/', include('userprofile.urls')),


    url(r'^hello/$', 'article.views.hello'),
    url(r'^hello_template/$', 'article.views.hello_template'),
    url(r'^hello_simple/$', 'article.views.hello_template_simple'),
    url(r'^hello_class_view/$', HelloTemplate.as_view()),

    # user auth urls
    url(r'^accounts/login/$', 'django_test.views.login'),
    url(r'^accounts/auth/$', 'django_test.views.auth_view'),
    url(r'^accounts/logout/$', 'django_test.views.logout'),
    url(r'^accounts/loggedin/$', 'django_test.views.loggedin'),
    url(r'^accounts/invalid/$', 'django_test.views.invalid'),

    # user registration
    url(r'^accounts/register/$', 'django_test.views.register_user'),
    url(r'^accounts/register_success/$', 'django_test.views.register_success'),

    # Formwizard:
    url(r'^contact/$',
        ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),

)


if not settings.DEBUG:
    from django.cotrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

article/models.py
from django.db import models
from time import time


def get_upload_file_name(instance, filename):
    return "uploaded_files/%s_%s" % (str(time()).replace('.', '_'), filename)


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('data published')
    likes = models.IntegerField(default=0)
    thumbnail = models.FileField(upload_to=get_upload_file_name)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/articles/%i/" % self.id


class Comment(models.Model):
    name = models.CharField(max_length=200)
    #first_name = models.CharField(max_length=200)
    #second_name = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    article = models.ForeignKey(Article)

    def __unicode__(self):
        return self.title


class Rating(models.Model):
    stars = models.IntegerField(default=0)
    article = models.ForeignKey(Article)

article/forms.py
# -*- coding: utf-8 -*-

from django import forms
from models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # which fields will be shown:
        fields = ('title', 'body', 'pub_date', 'thumbnail')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # which fields will be shown:
        fields = ('name', 'body')

article/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone

from django.template import RequestContext
from django.contrib import messages

from forms import ArticleForm, CommentForm
from article.models import Article, Comment
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf

import logging
logr = logging.getLogger(__name__)

# Create your views here.


def articles(request):
    language = 'en-gb'
    session_language = 'en-gb'

    if 'lang' in request.COOKIES:
        language = request.COOKIES['lang']

    if 'lang' in request.session:
        session_language = request.session['lang']


    args = {}
    args.update(csrf(request))
    args.update({
        'articles': Article.objects.all(),
        'language': language,
        'session_language': session_language})

    return render_to_response('articles.html', args)


def article(request, article_id=1):
    #return render_to_response('article.html',
                              #{'article': Article.objects.get(id=article_id) },
                              #context_instance=RequestContext(request))
    return render(request, 'article.html',
                  {'article': Article.objects.get(id=article_id) })


def language(req, language='en-gb'):
    response = HttpResponse("setting language to %s"  % language)
    response.set_cookie('lang', language)

    return response


### Procedural approach:

def hello(request):
    name = "Mike"
    html = "<html><body>Hi %s, thsi seams to have worked!</body></html>" % name
    return HttpResponse(html)


from django.template.loader import get_template
from django.template import Context

def hello_template(request):
    name = "Mike"
    t = get_template('hello.html')
    html = t.render(Context({'name': name}))
    return HttpResponse(html)


## OOP approach:

from django.views.generic.base import TemplateView

class HelloTemplate(TemplateView):

    template_name = "hello_class.html"

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        context['name'] = "Mike"
        return context

## With shortcuts:

def hello_template_simple(request):
    name = "Mike"
    return render_to_response('hello.html', {'name': name})


def create(req):
    if req.POST:
        form = ArticleForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/articles/all/')
    else:
        form = ArticleForm()

    args = {}
    args.update(csrf(req))

    args['form'] = form

    return render_to_response('create_article.html', args)


def like_article(req, article_id):

    if article_id:
        a = Article.objects.get(id=article_id)
        a.likes += 1
        a.save()

    return HttpResponseRedirect('/articles/get/%s' % article_id)


def add_comment(req, article_id):

    a = Article.objects.get(id=article_id)
    if req.POST:
        f = CommentForm(req.POST)
        if f.is_valid():
            c = f.save(commit=False)
            c.pub_date = timezone.now()
            c.article = a
            c.save()
            return HttpResponseRedirect('/articles/get/%s' % article_id)
    else:
        f = CommentForm()

    args = {}
    args.update(csrf(req))
    args['article'] = a
    args['form'] = f

    return render_to_response('add_comment.html', args)


def search_titles(req):
    if req.method == "POST":
        search_text = req.POST['search_text']
    else:
        search_text = ''

    articles = Article.objects.filter(title__contains=search_text)

    return render_to_response("ajax_search.html", {"articles": articles})

article/templates/add_comment.html
{% extends "base.html" %}

{% block sidebar %}
<ul><li><a href="/articles/get/{{article.id}}">Cancel</a></li></ul>
{% endblock %}

{% block content %}



<form action="/articles/add_comment/{{article.id}}/" method="post">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" nam="submit" value="Post Commment">

</from>


{% endblock %}

article/templates/ajax_search.html
{% if articles.count > 0 %}
  {% for a in articles %}<li><a href="/article/{{ a.id }}">{{ a.title }}</a>	</li>{% endfor %}
{% else %}<li>None to show ...</li>{% endif %}

article/templates/article.html
{% extends "base.html" %}

{% block content %}

<h1>{{ article.title }} ({{ id }})</h1>
<p>{{ article.body }}</p>

{% if article.thumbnail %}
<p><img src="/static/media/{{article.thumbnail}}" width="200" /></p>
{% endif %}

<p>{{article.likes}} people likes this article</p>
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
{% for c in article.comment_set.all %}
  <p>{{c.name}}: {{c.body}}</p>
{% endfor %}

<p><a href="/articles/add_comment/{{article.id}}">Add Comment</a></p>

{% endblock %}

article/templates/articles.html
{% extends "base.html" %}
{% load article_tags %}

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Articles</a></li>
    <li><a href="/articles/create">Create Article</a></li>
</ul>
<h3>Search</h3>
{% csrf_token %}
<input type="text" id="search" name="search" />

<ul id="search-results">
</ul>

{% endblock %}


{% block content %}
<h2>Language is: {{language}}</h2>
<h2>Session Language is: {{session_language}}</h2>
{% if articles.count > 0 %}
	{% for a in articles %}
	<div>
		<h2><a href="/article/{{ a.id }}">{{ a.title }} ({{ a.id }})</a></h2>

		<p>{{a.body|lower|article_shorten_body:"10" }}</p>
		<p>{{a.body|lower|truncatewords:"10" }}</p>
            <p>{{a.likes}} people likes this article</p>
	</div>
	{% endfor %}
{% else %}
<p>None to show ...</p>
{% endif %}
{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}

{% block content %}

<ul><li><a href="/articles/all">Cancel</a></li></ul>


<form action="/articles/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" nam="submit" value="Create Article">

</from>

{% endblock %}